#+TITLE: BunnEmacs
#+AUTHOR: PathologicalHandwaving
#+CATEGORY: Config
#+DATE_CREATED: [2020-07-06]
#+DATE_MODIFIED: [2020-07-26]

*BunnEmacs* is an opinionated, MacOS centric emacs configuration.
Developed under MacOS Catalina 10.15.6 using *Emacs* 28 HEAD (see README for installation steps).

By default it launches via emacsclient using a [[https://www.hammerspoon.org/][Hammerspoon]] keybinding (see details in README).

BunnEmacs is still in development but works great so far! Suggestions welcome!

BunnEmacs use-cases are focused on note taking, pdf annotation, and academic style research and development work with heavy use of embedded LaTeX code and shell scripts.
 
*NOTE:* BunnEmacs does not focus on org-export to LaTeX as a preference and uses LaTeX templates for academic document creation and referencing.

* Load Files

** Load =.custom.el=

One is able to use the customization interface that is bundled within Emacs. It
is meant to help people who are not familiar with Emacs Lisp in the
configuration of Emacs itself. By default, changes in the customization will be
automatically detected and appended at the end of the configuration file,
=init.el=.

Since that in my case, the actual configuration file is a new one, crafted by
=org-mode=, adding code at the end of =init.el= might mess things up. The
following tells Emacs to add extra code in another file that would be then
loaded, if existing.

#+BEGIN_SRC emacs-lisp
(setq-default custom-file (expand-file-name "custom.el" user-emacs-directory))
(when (file-exists-p custom-file)
  (load custom-file))
#+END_SRC


** Load =.secrets.el=


#+BEGIN_SRC emacs-lisp
(let ((secret.el (expand-file-name "secret.el" user-emacs-directory)))
  (when (file-exists-p secret.el)
    (load secret.el)))
#+END_SRC



* Startup Options

** Initial Size and Position
Startup in center of current screen

#+begin_src emacs-lisp
(defun bun-set-initial-frame ()
  (let* ((base-factor 0.70)
         (a-width (* (display-pixel-width) base-factor))
         (a-height (* (display-pixel-height) base-factor))
         (a-left (truncate (/ (- (display-pixel-width) a-width) 2)))
         (a-top (truncate (/ (- (display-pixel-height) a-height) 2))))
    (set-frame-position (selected-frame) a-left a-top)
    (set-frame-size (selected-frame) (truncate a-width) (truncate a-height) t)))
(setq frame-resize-pixelwise t)
(bun-set-initial-frame)
#+end_src

** Startup Buffer
#+begin_src emacs-lisp

#+end_src

** Startup message
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)
#+END_SRC

** Scratch Message
#+BEGIN_SRC emacs-lisp
(setq-default initial-scratch-message "")
#+END_SRC

** Bar Modes
#+BEGIN_SRC emacs-lisp
(menu-bar-mode +1)
(tool-bar-mode -1)
(tooltip-mode +1)
#+END_SRC


#+BEGIN_SRC emacs-lisp
(size-indication-mode t)
#+END_SRC

** Scroll-bar Mode
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
(setq scroll-margin 3
      scroll-conservatively 10000
      scroll-preserve-screen-position 1)
#+END_SRC

** Highlight Current Line
#+BEGIN_SRC emacs-lisp
(add-hook 'after-init-hook 'global-hl-line-mode)
#+END_SRC

** Line Numbers
#+BEGIN_SRC emacs-lisp
(line-number-mode +1)
(global-display-line-numbers-mode 1)
(column-number-mode t)
#+END_SRC

** Wrapping
#+BEGIN_SRC emacs-lisp
(global-visual-line-mode t)
#+END_SRC

*** Do not trunate lines and word wrap
#+begin_src emacs-lisp
(set-default 'truncate-lines nil)
(set-default 'word-wrap t)
(setq helm-buffers-truncate-lines nil)
#+end_src

** Encoding
#+BEGIN_SRC emacs-lisp
(prefer-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(setq locale-coding-system 'utf-8)
#+END_SRC

** Exec Path From Shell
#+BEGIN_SRC emacs-lisp
(use-package exec-path-from-shell
  :config
  (exec-path-from-shell-initialize))
#+END_SRC

** Garbage Collection
*** If not in focus, garbage collect
#+BEGIN_SRC emacs-lisp
(add-hook 'focus-out-hook #'garbage-collect)
#+END_SRC

** Large File Warning
#+BEGIN_SRC emacs-lisp
(setq large-file-warning-threshold 100000000)
#+END_SRC

** Yes-or-No
#+BEGIN_SRC emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

** Editing
*** Use spaces
#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
#+end_src

*** Newline at end of file
#+BEGIN_SRC emacs-lisp
(setq require-final-newline t)
#+END_SRC

** Security
#+begin_src emacs-lisp
(progn
(setq org-confirm-babel-evaluate nil)
(setq org-confirm-elisp-link-function nil)
(setq org-confirm-shell-link-function nil))
#+end_src

** Server

** Lisp APIs
Package dependencies providing modern APIs for working with lisp structures

#+begin_src emacs-lisp
(require 'cl-lib)
(use-package f :demand t)        ; files
(use-package dash :demand t)     ; lists
(use-package ht :demand t)       ; hash-tables
(use-package s :demand t)        ; strings
(use-package a :demand t)        ; association lists
(use-package anaphora :demand t) ; enables temp variables
#+end_src

** Directory Variables

*** Home Directory Variables
#+begin_src emacs-lisp
(defvar bunny-home-dir (expand-file-name "~/"))
(defvar bunny-emacs-dir (concat bunny-home-dir ".emacs.d/"))
(defvar bunny-librarian (concat bunny-home-dir "Librarian/"))
(defvar bunny-pictures-dir (concat bunny-home-dir "Pictures/"))
(defvar bunny-movies-dir (concat bunny-home-dir "Movies/"))
(defvar bunny-music-dir (concat bunny-home-dir "Music/"))
(defvar bunny-progz-dir (concat bunny-home-dir "Progz/"))
(defvar bunny-repos-dir (concat bunny-home-dir "Repos/"))
(defvar bunny-sites-dir (concat bunny-home-dir "Sites/"))
(defvar bunny-torrents-dir (concat bunny-home-dir "Torrents/"))
(defvar bunny-org-dir (concat bunny-home-dir "OrgDB/"))

#+end_src

*** OrgDB Directory Variables
#+begin_src emacs-lisp
(defvar bunny-adhd-dir (concat bunny-org-dir "ADHD/"))
(defvar bunny-archive-dir (concat bunny-org-dir "Archive/"))
(defvar bunny-code-dir (concat bunny-org-dir "Code/"))
(defvar bunny-dmp-dir (concat bunny-org-dir "DMP/"))
(defvar bunny-invest-dir (concat bunny-org-dir "Investigations/"))
(defvar bunny-inbox-dir (concat bunny-org-dir "Inbox/"))
(defvar bunny-lldb-dir (concat bunny-org-dir "LLDB/"))
(defvar bunny-lists-dir (concat bunny-org-dir "Lists/"))
(defvar bunny-logs-dir (concat bunny-org-dir "Logs/"))
(defvar bunny-notes-dir (concat bunny-org-dir "Notes/"))
(defvar bunny-paperless-dir (concat bunny-org-dir "Paperless/"))
(defvar bunny-projects-dir (concat bunny-org-dir "Projects/"))
(defvar bunny-tmp-dir (concat bunny-org-dir "TMP/"))
(defvar bunny-templates-dir (concat bunny-org-dir "Templates/"))
(defvar bunny-work-dir (concat bunny-org-dir "Work/"))
#+end_src

*** Librarian Directory Variables
#+begin_src emacs-lisp
(defvar bunny-articles-dir (concat bunny-librarian "Articles/"))
(defvar bunny-bib-dir (concat bunny-librarian "Bibliography/"))
(defvar bunny-data-dir (concat bunny-librarian "Data/"))
(defvar bunny-dictionary-dir (concat bunny-librarian "Dictionary/"))
(defvar bunny-legis-dir (concat bunny-librarian "Legis/"))
(defvar bunny-pdfs-dir (concat bunny-librarian "PDFs/"))
(defvar bunny-quotes-dir (concat bunny-librarian "Quotes/"))
(defvar bunny-text-dir (concat bunny-librarian "Text/"))
(defvar bunny-webarchives-dir (concat bunny-librarian "WebArchives/"))
(defvar bunny-epubs-dir (concat bunny-librarian "ePubs/"))
#+end_src

*** Movies Directory Variables
#+begin_src emacs-lisp
(defvar bunny-films-dir (concat bunny-movies-dir "Films/"))
(defvar bunny-lectures-dir (concat bunny-movies-dir "Lectures/"))
(defvar bunny-tv-dir (concat bunny-movies-dir "TV/"))
(defvar bunny-talks-dir (concat bunny-movies-dir "Talks/"))
#+end_src

*** Music Directory Variables
#+begin_src emacs-lisp
(defvar bunny-audiobooks-dir (concat bunny-music-dir "AudioBooks/"))
(defvar bunny-songs-dir (concat bunny-music-dir "Music/"))
(defvar bunny-sounds-dir (concat bunny-music-dir "Sounds/"))
#+end_src

*** Sites Directory Variables
#+begin_src emacs-lisp
(defvar bunny-content-dir (concat bunny-sites-dir "Content/"))
(defvar bunny-devl-dir (concat bunny-sites-dir "Devl/"))
(defvar bunny-drafts-dir (concat bunny-sites-dir "Drafts/"))
(defvar bunny-production-dir (concat bunny-sites-dir "Production/"))
#+end_src

** File Variables
*** Create file-name variable relative to org directory
#+begin_src emacs-lisp
(defun bunny-org-file-name (file-name)
"Create file-name relative to bunny-org-dir"
(concat bunny-org-dir file-name))
#+end_src

*** Create file-name variable relative to librarian directory
#+begin_src emacs-lisp
(defun bunny-librarian-file-name (file-name)
"Create file-name relative to bunny-librarian directory"
(concat bunny-librarian file-name))
#+end_src


*** notes-file
#+begin_src emacs-lisp
(defvar bunny-notes-file
(bunny-org-file-name "Notes/notes.org")
"Notes catcher file-name")
#+end_src

*** inbox-file
#+begin_src emacs-lisp
(defvar bunny-inbox-file
(bunny-org-file-name "Inbox/inbox.org")
"Inbox catcher file-name")
#+end_src

*** agenda-file
#+begin_src emacs-lisp
(defvar bunny-agenda-file
(bunny-org-file-name "Inbox/agenda.org")
"Agenda catcher file-name")
#+end_src

*** ideas-file
#+begin_src emacs-lisp
(defvar bunny-ideas-file
(bunny-org-file-name "Inbox/ideas.org")
"Ideas catcher file-name")
#+end_src

*** todos-file
#+begin_src emacs-lisp
(defvar bunny-todos-file
(bunny-org-file-name "Inbox/todos.org")
"Todos catcher file-name")
#+end_src

*** recipes-file
#+begin_src emacs-lisp
(defvar bunny-recipes-file
(bunny-org-file-name "Inbox/recipes.org")
"Recipes file-name")
#+end_src

*** remember-file
#+BEGIN_SRC emacs-lisp
(defvar bunny-remember-file
(bunny-org-file-name "Inbox/remember.org")
"remember file-name")
#+END_SRC

*** routine-file
#+begin_src emacs-lisp
(defvar bunny-routine-file
(bunny-org-file-name "Inbox/routine.org")
"routine file-name")
#+end_src

*** holidays-file
#+begin_src emacs-lisp
(defvar bunny-holidays-file
(bunny-org-file-name "Inbox/holidays.org")
"Holidays file-name")
#+end_src

*** log-file
#+begin_src emacs-lisp
(defvar bunny-log-file
(bunny-org-file-name "Logs/log.org")
"Log catcher file-name")
#+end_src

*** investigations-file
#+begin_src emacs-lisp
(defvar bunny-invest-file
(bunny-org-file-name "Investigations/investigations.org")
"Investigations list file-name")
#+end_src

*** lldb-file
#+begin_src emacs-lisp
(defvar bunny-lldb-file
(bunny-org-file-name "LLDB/lldb.org")
"LLDB file-name")
#+end_src

*** Lists Index File
#+begin_src emacs-lisp
(defvar bunny-lists-index-file
(bunny-org-file-name "Lists/index.org")
"Lists index file-name")
#+end_src

*** projects-list-file
#+begin_src emacs-lisp
(defvar bunny-project-list-file
(bunny-org-file-name "Projects/projects.org")
"Projects list file-name")
#+end_src

*** Templates Index File
#+begin_src emacs-lisp
(defvar bunny-templates-index-file
(bunny-org-file-name "Templates/index.org")
"Templates index file-name")
#+end_src

*** Observations File
#+begin_src emacs-lisp
(defvar bunny-observations-file
(bunny-org-file-name "Logs/observations.org")
"observations file-name")
#+end_src

*** PDFs Index File
#+begin_src emacs-lisp
(defvar bunny-pdfs-index-file
(bunny-librarian-file-name "PDFs/index.org")
"PDFs Index file-name")
#+end_src

*** Articles Index File
#+begin_src emacs-lisp
(defvar bunny-articles-index-file
(bunny-librarian-file-name "Articles/index.org")
"Articles Index file-name")
#+end_src

*** Data Index File
#+begin_src emacs-lisp
(defvar bunny-data-index-file
(bunny-librarian-file-name "Data/index.org")
"Data Index file-name")
#+end_src

*** Dictionary Index File
#+begin_src emacs-lisp
(defvar bunny-dictionary-index-file
(bunny-librarian-file-name "Dictionary/index.org")
"Dictionary Index file-name")
#+end_src

*** Legis Index File
#+begin_src emacs-lisp
(defvar bunny-legis-index-file
(bunny-librarian-file-name "Legis/index.org")
"Legis Index file-name")
#+end_src

*** Quotes Index File
#+begin_src emacs-lisp
(defvar bunny-quotes-index-file
(bunny-librarian-file-name "Quotes/index.org")
"Quotes Index file-name")
#+end_src

*** Text Index File
#+begin_src emacs-lisp
(defvar bunny-text-index-file
(bunny-librarian-file-name "Text/index.org")
"Text Index file-name")
#+end_src

*** ePubs Index File
#+begin_src emacs-lisp
(defvar bunny-epubs-index-file
(bunny-librarian-file-name "ePubs/index.org")
"ePubs Index file-name")
#+end_src

*** feeds.org
#+begin_src emacs-lisp
(defvar bunny-elfeed-org-files
(bunny-librarian-file-name "feeds.org")
"feeds.org file-name")
#+end_src

*** ADHD Log
#+begin_src emacs-lisp
(defvar bunny-adhd-log-file 
(bunny-org-file-name "ADHD/log.org")
"ADHD log file-name")
#+end_src

** Golden Ratio
#+begin_src emacs-lisp
(use-package golden-ratio
  :ensure t
  :config
  (golden-ratio-mode 1)
  (setq golden-ratio-auto-scale t)
  (setq golden-ratio-max-width 72))
#+end_src

* MacOS UI
#+BEGIN_SRC emacs-lisp
(add-to-list 'default-frame-alist '(ns-transparent-titlebar . t))
#+END_SRC

** Transparency
#+BEGIN_SRC emacs-lisp
(modify-frame-parameters (selected-frame) '((alpha . 75)))
(add-to-list 'default-frame-alist '(alpha 85 85))
#+END_SRC

** Meta
#+BEGIN_SRC emacs-lisp
(setq ns-function-modifer 'hyper)
#+END_SRC

** Swap meta and super
#+BEGIN_SRC emacs-lisp
(setq mac-option-modifer 'meta)
(setq mac-command-modifer 'super)
#+END_SRC


* Theme

** Default Theme
#+BEGIN_SRC emacs-lisp
(use-package doom-themes
  :ensure t
  :config
  (setq doom-themes-enable-bold t
        doom-themes-enable-italic t)
  (doom-themes-neotree-config)
  (setq doom-neotree-enable-file-icons t)
  (setq doom-neotree-enable-chevron-icons t)
  (setq doom-neotree-enable-type-colors t)
  (doom-themes-org-config))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(load-theme 'doom-outrun-electric t)
#+END_SRC

** Neotree
#+BEGIN_SRC emacs-lisp
(use-package neotree
  :bind ("C-x n" . neotree-toggle)
  :config
  (neotree-dir "~/.emacs.d"))
#+END_SRC

#+begin_src emacs-lisp
(global-set-key [f8] 'neotree-toggle)
#+end_src

#+begin_src emacs-lisp
(defun neotree-startup ()
  (interactive)
  (neotree-show)
  (call-interactively 'other-window))
(if (daemonp)
    (add-hook 'server-switch-hook #'neotree-startup)
  (add-hook 'after-init-hook #'neotree-startup))
#+end_src

#+BEGIN_SRC emacs-lisp
(use-package all-the-icons)
#+END_SRC

#+begin_src emacs-lisp
(setq neo-theme (if (display-graphic-p) 'icons 'arrow))
#+end_src

** Nyan-Mode
#+BEGIN_SRC emacs-lisp
(use-package nyan-mode
  :config
  (nyan-mode 1)
  (nyan-toggle-wavy-trail)
  (nyan-start-animation))
#+END_SRC

** Parens
#+BEGIN_SRC emacs-lisp
(use-package rainbow-delimiters)
#+END_SRC

** Modeline
#+begin_src emacs-lisp
(use-package doom-modeline
  :ensure t
  :init (doom-modeline-mode 1))
#+end_src


* Keybinds

** GoTo Next Window
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x o") (lambda ()
                                (interactive)
				(other-window -1)))
#+END_SRC


** Replace buffer menu with ibuffer
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x C-b") 'ibuffer)
#+END_SRC

** Symbol Insert
#+BEGIN_SRC emacs-lisp
(define-key global-map (kbd "C-c M-3") (lambda () (interactive) (insert "§")))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(define-key global-map (kbd "C-c M-4") (lambda () (interactive) (insert "↯")))
#+END_SRC


** Delete Frame
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-x w") 'delete-frame)
#+END_SRC

** Copy Mouse Selected Text Automatically
#+BEGIN_SRC emacs-lisp
(setq mouse-drag-copy-region t)
#+END_SRC

** Orgmode
*** agenda
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c a") 'org-agenda)
#+END_SRC

*** capture
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c c") 'org-capture)
#+END_SRC

#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "C-c l") 'org-store-link)
#+END_SRC



* Help
#+BEGIN_SRC emacs-lisp
(use-package help-mode
  :ensure nil
  :bind
  (:map help-mode-map
        ("<" . help-go-back)
        (">" . help-go-forward)))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package eldoc
  :ensure nil
  :config
  (global-eldoc-mode -1))
#+END_SRC

#+begin_src emacs-lisp
(require 'dash-docs)
(setq dash-docs-browser-func 'eww)
#+end_src

* Expand
** Helm
#+begin_src emacs-lisp
(use-package helm
  :diminish
  :init (helm-mode t)
  :bind (("M-x" . helm-M-x)
	     ("C-x C-f" . helm-find-files)
	     ("C-x b" . helm-mini)
	     ("C-x C-r" . helm-recentf)
	     ("C-c i" . helm-imenu)
	     ("M-y" . helm-show-kill-ring)
	     ("C-c o" . helm-occur)
	     ("C-x r b" . helm-bookmarks)
	     ("C-c R" . helm-register))
  :config
  (helm-autoresize-mode 1))
#+end_src
*** helm-posframe
#+begin_src emacs-lisp
(require 'helm-posframe)
(helm-posframe-enable)
#+end_src

*** helm-icons
#+begin_src emacs-lisp
(require 'helm-icons)
(helm-icons-enable)
#+end_src

*** Helm-Org
#+begin_src emacs-lisp
(use-package helm-org
  :config
  (add-to-list 'helm-completing-read-handlers-alist '(org-capture . helm-org-completing-read-tags))
  (add-to-list 'helm-completing-read-handlers-alist '(org-set-tags . helm-org-completing-read-tags)))
#+end_src

*** Helm-Themes
#+begin_src emacs-lisp
(use-package helm-themes)
#+end_src

*** Helm-descbinds
#+begin_src emacs-lisp
(use-package helm-descbinds
  :demand
  :config
  (helm-descbinds-mode))
#+end_src

*** Helm-org-rifle
#+begin_src emacs-lisp
(use-package helm-org-rifle
  :after (helm org)
  :commands helm-org-rifle-current-buffer
  :config
  (define-key org-mode-map (kbd "M-r") 'helm-org-rifle-current-buffer))
#+end_src

*** Helm-ls-git
#+begin_src emacs-lisp
(require 'helm-ls-git)
(global-set-key (kbd "C-x C-d") 'helm-browse-project)
(global-set-key (kbd "C-x r p") 'helm-projects-history)
#+end_src


** YaSnippets
#+BEGIN_SRC emacs-lisp
(use-package yasnippet
  :ensure t
  :init
  (yas-global-mode 1)
  :config
  (add-to-list 'yas-snippet-dirs (locate-user-emacs-file "snippets")))
#+END_SRC

** Auto-Complete
#+BEGIN_SRC emacs-lisp
(use-package company
  :bind
  (:map company-active-map
        ("RET" . nil)
        ([return] . nil)
        ("TAB" . company-complete-selection)
        ([tab] . company-complete-selection)
        ("<right>" . company-complete-common))
  :hook
  (after-init . global-company-mode)
  :custom
  (company-dabbrev-downcase nil)
  (company-idle-delay .2)
  (company-minimum-prefix-length 2)
  (company-tooltip-limit 10)
  (company-show-numbers t)
  (company-require-match nil)
  (company-tooltip-align-annotations t)
  (company-tooltip-flip-when-above t))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(global-company-mode 1)
#+END_SRC

** Which-key
#+BEGIN_SRC emacs-lisp
(use-package which-key
  :config
  (setq which-key-popup-type 'minibuffer)
  (setq which-key-frame-max-height 20)
  (which-key-mode +1))
#+END_SRC


#+BEGIN_SRC emacs-lisp
(use-package smex
  :bind
  ("M-x" . 'smex)
  ("M-X" . 'smex-major-mode-commands)
  :config
  (setq smex-save-file (expand-file-name ".smex-items" user-emacs-directory))
  (smex-initialize))
#+END_SRC

** Crux
#+BEGIN_SRC emacs-lisp
(use-package crux
  :bind (("C-a" . crux-move-beginning-of-line)
	     ("C-c u" . crux-view-url)
	     ("C-c k" . crux-kill-other-buffers)
	     ("C-c i" . crux-ispell-word-then-abbrev)
	     ("C-x C-u" . crux-upcase-region)
	     ("C-x C-l" . crux-downcase-region)
	     ("C-c r" . crux-rename-file-and-buffer)
	     ("C-c D" . crux-delete-file-and-buffer)
	     ("C-k" . crux-smart-kill-line)))
#+END_SRC

** Abbrev
#+BEGIN_SRC emacs-lisp
(setq save-abbrevs 'silently)
(setq-default abbrev-mode t)
(setq abbrev-file-name "~/.emacs.d/abbreviations.el")
(quietly-read-abbrev-file)
#+END_SRC


* Search

** Dictionary
#+BEGIN_SRC emacs-lisp
(use-package define-word)
#+END_SRC

** Translate
#+BEGIN_SRC emacs-lisp
(use-package google-translate)
#+END_SRC


** Google-This
#+BEGIN_SRC emacs-lisp
(use-package google-this
  :config
  (google-this-mode 1))
#+BEGIN_SRC 


* Utilities

** gitignore-templates
#+begin_src emacs-lisp
(require 'gitignore-templates)
(setq gitignore-templates-api 'github)
#+end_src

** git-gutter-fringe
Enable global minor mode

#+begin_src emacs-lisp
(require 'git-gutter)
(global-git-gutter-mode +1)
(global-set-key (kbd "C-x C-g") 'git-gutter)
(global-set-key (kbd "C-x v =") 'git-gutter:popup-hunk)
(global-set-key (kbd "C-x p") 'git-gutter:previous-hunk)
(global-set-key (kbd "C-x n") 'git-gutter:next-hunk)
(global-set-key (kbd "C-x v s") 'git-gutter:stage-hunk)
(global-set-key (kbd "C-x v r") 'git-gutter:revert-hunk)
(add-to-list 'git-gutter:update-hooks 'focus-in-hook)
#+end_src

#+RESULTS:
: git-gutter-fringe

** git-autocommit-mode
#+begin_src emacs-lisp
(require 'git-auto-commit-mode)
(setq-default gac-automatically-push-p t)
#+end_src

** org-attach-git
#+begin_src emacs-lisp
(require 'org-attach-git)
#+end_src

** helm-github-stars
#+begin_src emacs-lisp
(require 'helm-github-stars)
(setq helm-github-stars-username "pathologicalhandwaving")
(setq helm-github-stars-refetch 10.0)
(setq helm-github-stars-name-length 17)
#+end_src

** rfc-mode
#+begin_src emacs-lisp
(use-package rfc-mode
  :init
  (setq rfc-mode-directory (expand-file-name "~/Librarian/Dictionary/RFCs/")
        rfc-mode-index-path (concat rfc-mode-directory "rfc-index.org")))
#+end_src

** Bookmarks
#+BEGIN_SRC emacs-lisp
(use-package ebuku)
#+END_SRC

*** bm visible bookmarks
#+BEGIN_SRC emacs-lisp
(use-package bm
  :bind (("<C-f2>" . bm-toggle)
         ("<f2>" . bm-next)
	 ("<S-f2>" . bm-previous)))
#+END_SRC

*** Helm-bookmarks
#+begin_src emacs-lisp
(with-eval-after-load 'helm
(require 'helm-bookmark)
(global-set-key (kbd "C-x C-b") 'helm-bookmark))
#+end_src

*** eBuku
#+begin_src emacs-lisp
(setq ebuku-buku-path "/usr/local/bin/buku")
(setq ebuku-database-path "/Users/emd/.local/share/buku/bookmarks.db")
#+end_src
** Kill
#+BEGIN_SRC emacs-lisp
(use-package easy-kill)
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (global-set-key [remap kill-ring-save] 'easy-kill)
  (global-set-key [remap mark-sexp] 'easy-mark)
#+END_SRC

** Clipboard
Save current system clipboard to kill-ring
#+BEGIN_SRC emacs-lisp
(setq save-interprogram-paste-before-kill t)
#+END_SRC

** wttrin
#+BEGIN_SRC emacs-lisp
(use-package wttrin
  :ensure t
  :commands (wttrin)
  :init
  (setq wttrin-default-cities '("Durham,NC")))
#+END_SRC

** AutoSave
#+begin_src emacs-lisp
(setq auto-save-default t)
#+end_src

Autosave every 30 seconds
#+begin_src emacs-lisp
(setq auto-save-timeout 30)
#+end_src

Auto save after 30 typed characters
#+BEGIN_SRC emacs-lisp
(setq auto-save-interval 30)
#+END_SRC

Autosaves in same place
#+begin_src emacs-lisp
(defvar emacs-autosave-directory
(concat user-emacs-directory "autosaves/"))
(unless (file-exists-p emacs-autosave-directory)
(make-directory emacs-autosave-directory))
#+end_src

** Backups
Set backups directory
#+begin_src emacs-lisp
(setq backup-directory-alist `((".*" . ,emacs-autosave-directory)))
#+end_src

#+BEGIN_SRC emacs-lisp
(setq backup-by-copying t)
(setq kept-new-versions 10)
(setq kept-old-versions 0)
(setq delete-old-versions t)
(setq version-control t)
(setq vc-make-backup-files t)
#+END_SRC

Backup after every save
#+begin_src emacs-lisp
(use-package backup-each-save
  :config (add-hook 'after-save-hook 'backup-each-save))
#+end_src

** Scratch Buffer
#+BEGIN_SRC emacs-lisp
(setq initial-major-mode 'org-mode)
#+END_SRC

** Volatile Highlights
Temporarily highlight changes to buffer after pasting
#+BEGIN_SRC emacs-lisp
(use-package volatile-highlights
  :config
  (volatile-highlights-mode t))
#+END_SRC

** Timers
#+begin_src emacs-lisp
(require 'chronos)
#+end_src

#+begin_src emacs-lisp
(use-package helm-chronos
  :ensure t
  :init (setq helm-chronos-standard-timers
              '("       5/Coffee"
                "       30/Shower"
                "       25/Email"
                "       27/Pom: Work + 7/Pom: Rest"))
  :bind (("C-c t" . helm-chronos-add-timer)))
#+end_src

** Alarm Clock
#+begin_src emacs-lisp
(require 'alarm-clock)
#+end_src

** Structure Templates
#+BEGIN_SRC emacs-lisp
(require 'org-tempo)
#+END_SRC


** hypothesis
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/vendor/hypothesis/hypothesis.el")
(setq hypothesis-username "kmshort")
(setq hypothesis-token "6879-9dGOKdgnYcGUyl0y_ljTPEAzJmlzATFxy7sOA-oyoq8")
#+end_src


* Languages
  
** BibTeX



** CSS

#+BEGIN_SRC emacs-lisp
(use-package css-mode
  :ensure nil
  :custom (css-indent-offset 2))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package scss-mode
  :ensure nil
  :preface
  (defun bunny/scss-set-comment-style ()
    (setq-local comment-end "")
    (setq-local comment-start "//"))
  :mode ("\\.sass\\'" "\\.scss\\'")
  :hook (scss-mode . bunny/scss-set-comment-style))
#+END_SRC


** CSV
#+BEGIN_SRC emacs-lisp
(use-package csv-mode)
#+END_SRC


** Colors
Colorize colors as text with their value
#+BEGIN_SRC emacs-lisp
(use-package rainbow-mode
  :custom
  (rainbow-x-colors-major-mode-list '()))
#+END_SRC


** Comments
#+BEGIN_SRC emacs-lisp
(use-package newcomment
  :ensure nil
  :bind
  ("<M-return>" . comment-indent-new-line)
  :custom
  (comment-auto-fill-only-comments t)
  (comment-multi-line t))
#+END_SRC


** Diff
#+BEGIN_SRC emacs-lisp
(use-package ediff-wind
  :ensure nil
  :custom
  (ediff-split-window-function #'split-window-horizontally)
  (ediff-window-setup-function #'ediff-setup-windows-plain))
#+END_SRC


** HTML
HTML mode is defined in =sgml-mode.el=

#+BEGIN_SRC emacs-lisp
(use-package sgml-mode
  :ensure nil
  :preface
  (defun bunny/html-set-pretty-print-function ()
    (setq bunny/pretty-print-function #'sgml-pretty-print))
  :hook
  ((html-mode . bunny/html-set-pretty-print-function)
   (html-mode . sgml-electric-tag-pair-mode)
   (html-mode . sgml-name-8bit-mode)
   (html-mode . toggle-truncate-lines))
  :custom
  (sgml-basic-offset 2))
#+END_SRC


** JSON

#+BEGIN_SRC emacs-lisp
(use-package json-mode
  :mode "\\.json\\'"
  :preface
  (defun bunny/json-set-indent-level ()
    (setq-local js-indent-level 2))
  :hook (json-mode . bunny/json-set-indent-level))
#+END_SRC


** LaTeX
*** LaTeX Path
#+begin_src emacs-lisp
(setenv "PATH" (concat ":/Library/TeX/texbin/" (getenv "PATH")))
(add-to-list 'exec-path "/Library/TeX/texbin/")
#+end_src

*** Highlight LaTeX in Org
#+BEGIN_SRC emacs-lisp
(setq org-highlight-latex-and-related '(latex bibtex))
#+END_SRC


** Lisp
#+BEGIN_SRC emacs-lisp
(use-package ielm
  :ensure nil
  :hook (ielm-mode . (lambda () (setq-local scroll-margin 0))))
#+END_SRC


** OrgMode
*** Startup
#+begin_src emacs-lisp
(setq org-directory "~/OrgDB")
(setq org-default-notes-file (concat org-directory "/Notes/notes.org"))
#+end_src

  #+BEGIN_SRC emacs-lisp
  (add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
  #+END_SRC
**** Indented
   #+begin_src emacs-lisp
   (require 'org-indent)
   (setq org-startup-indented t)
   #+end_src
**** Truncated
#+begin_src emacs-lisp
(setq org-startup-truncated nil)
#+end_src

**** Folded
#+begin_src emacs-lisp
(setq org-startup-folded t)
#+end_src

*** Archives
#+begin_src emacs-lisp
(setq org-archive-location "~/OrgDB/Archive/agenda.org_archive::datetree/* Completed Tasks")
#+end_src

*** Babel
**** TODO Add plantuml path

 =(setq org-plantuml-jar-path "/usr/local/Cellar/plantuml/1.2018.3/libexec/plantuml.jar")=

*** Capture
#+begin_src emacs-lisp
(defun bun-create-notes-file ()
"Create an org file in ~/OrgDB/Notes."
  (interactive)
  (let ((name (read-string "File Name: ")))
    (expand-file-name (format "%s.org" name) "~/OrgDB/Notes/")))
#+end_src

#+begin_src emacs-lisp
(setq org-capture-templates
  '(("t" "ToDo" entry (file+headline "~/OrgDB/Inbox/todos.org" "ToDos")
     "** TODO %?\n")
    ("a" "Appointment" entry (file+headline "~/OrgDB/Inbox/agenda.org" "Appointments")
     "** APPOINTMENT %?\n %a")
    ("c" "Cookbook" entry (file "~/OrgDB/Chef/cookbook.org")
     "** %^{Recipe Title: }\n   :PROPERTIES:\n   :URL:\n   :SERVINGS:\n   :PREP_TIME:\n   :COOK_TIME:\n  :END:\n*** Ingredients\n    %?\n*** Directions\n\n")
    ("n" "Note" entry (file+headline "~/OrgDB/Notes/notes.org" "Notes")
     "** NOTE %x\n   :PROPERTIES:\n   :DATE: %U\n   :END:\n" :empty-lines 1)))
#+end_src

*** Links
#+begin_src emacs-lisp
(setq org-descriptive-links t)
#+end_src

*** Refile
*** Org-Chef
#+begin_src emacs-lisp
(use-package org-chef
  :ensure t)
#+end_src

*** Grammar and Spelling
**** Dont spell check these regions

 #+BEGIN_SRC emacs-lisp
(add-to-list 'ispell-skip-region-alist '(":\\(PROPERTIES\\|LOGBOOK\\):" . ":END:"))
(add-to-list 'ispell-skip-region-alist '("#\\+BEGIN_SRC" . "#\\+END_SRC"))
(add-to-list 'ispell-skip-region-alist '("#\\+BEGIN_EXAMPLE" . "#\\+END_EXAMPLE"))
 #+END_SRC

*** Layout
**** Modify demote bullets
 #+BEGIN_SRC emacs-lisp
(setq org-list-demote-modify-bullet '(("-" . "+")
                                      ("+" . "*")
				      ("*" . "-")))
 #+END_SRC

**** hide emphasis markers
 #+BEGIN_SRC emacs-lisp
(setq org-hide-emphasis-markers t)
 #+END_SRC

**** org-src block fontify
 #+BEGIN_SRC emacs-lisp
(setq org-src-fontify-natively t)
(setq org-src-tab-acts-natively t)
(setq org-edit-src-content-indentation 0)
(setq org-src-preserve-indentation t)
 #+END_SRC

**** fontify headlines
 #+BEGIN_SRC emacs-lisp
(setq org-fontify-whole-headline t)
 #+END_SRC

 #+BEGIN_SRC emacs-lisp
(setq org-fontify-done-headline t)
 #+END_SRC

**** fontify quote and verse blocks
 #+BEGIN_SRC emacs-lisp
(setq org-fontify-quote-and-verse-blocks t)
 #+END_SRC

**** Maximize description list indent
 #+BEGIN_SRC emacs-lisp
(setq org-list-description-max-indent 5)
 #+END_SRC

**** Checkbox Stats
#+begin_src emacs-lisp
(setq org-checkbox-hierarchical-statistics nil)
#+end_src

*** Keywords
#+begin_src emacs-lisp
(setq org-todo-keywords
      '((sequence "TODO" "|" "DONE")
	      (sequence "FIXME" "|" "FIXED")
        (sequence "ADD" "|" "ADDED")
        (sequence "REMOVE" "|" "REMOVED")
        (sequence "MOVE" "|" "MOVED")))
#+end_src

*** Agenda
**** Warn if deadline within next 7 days
#+BEGIN_SRC emacs-lisp
(setq org-deadline-warning-days 7)
#+END_SRC

**** Show all tasks due in next two weeks
#+BEGIN_SRC emacs-lisp
(setq org-agenda-span 7)
#+END_SRC

**** Dont show tasks as scheduled if they are categorized with a deadline
#+BEGIN_SRC emacs-lisp
(setq org-agenda-skip-scheduled-if-deadline-is-shown t)
#+END_SRC

**** Priority 
 #+BEGIN_SRC emacs-lisp
(setq org-highest-priority ?A)
(setq org-lowest-priority ?C)
(setq org-default-priority ?A)
 #+END_SRC

*** Org Files

default org directory
#+BEGIN_SRC emacs-lisp
(setq org-directory "/Users/emd/OrgDB/")
#+END_SRC

Agenda file

#+BEGIN_SRC emacs-lisp
(setq org-agenda-files (list org-directory))
#+END_SRC

Notes file

#+BEGIN_SRC emacs-lisp
(setq org-default-notes-file (concat org-directory "/Notes/notes.org"))
#+END_SRC

*** Refile
#+begin_src emacs-lisp
(setq org-refile-allow-creating-parent-nodes 'confirm)
(setq org-refile-targets '((nil :maxlevel . 9)
			         (org-agenda-files :maxlevel . 9)))
(setq org-outline-path-complete-in-steps nil)
(setq org-refile-use-outline-path '(file))
#+end_src

*** Utilities
**** PopOrg
 #+BEGIN_SRC emacs-lisp
(use-package poporg
  :bind (("C-c /" . poporg-dwim)))
 #+END_SRC

*** Reference
**** org-books
#+begin_src emacs-lisp
(require 'org-books)
(setq org-books-file "~/Librarian/index.org")
#+end_src

***** Adding new source
A source for books provide a details function that takes certain input (like a url in case of amazon) and returns a list of title, author and props. 
props is an alist which gets added to the entry as org properties. Here is the output from amazon’s:

=(print (org-books-get-details-amazon "https://www.amazon.in/Algebra-Chapter-Graduate-Studies-Mathematics/dp/0821847813/"))=

=("Algebra: Chapter 0 (Graduate Studies in Mathematics)" "Paolo Aluffi" (("AMAZON" . "https://www.amazon.in/Algebra-Chapter-Graduate-Studies-Mathematics/dp/0821847813/")))=

With the details function defined, you need to write the url pattern it accepts and add it to the variable =org-books-url-pattern-dispatches=. 

Check variable’s docstring for more details.

As of now there are the following sources:

- Manual (input: title, author etc.)
- Amazon (input: url)
- Goodreads (input: url)
- Openlibrary (input: url)
- ISBN (input: ISBN, dispatches openlibrary url source)
***** Capture

#+begin_verse
(setq org-capture-templates
      '(("b" "Book" entry (file "some-file.org")
         "* %^{TITLE}\n:PROPERTIES:\n:ADDED: %<[%Y-%02m-%02d]>\n:END:%^{AUTHOR}p\n%?" :empty-lines 1)))
#+end_verse

#+begin_verse
(setq org-capture-templates
      '(("b" "Book" entry (file "some-file.org")
         "%(let* ((url (substring-no-properties (current-kill 0)))
                  (details (org-books-get-details url)))
             (when details (apply #'org-books-format 1 details)))")))
#+end_verse


- To add books manually, use =org-books-add-book function=.
- To add from urls, call =org-books-add-url= (or use =org-books-cliplink= if url is in clipboard).
- To give ratings, go to the entry and call =org-books-rate-book=.
- While filing a book, =org-books-file-depth= tells which headings are to be considered as a category (like fiction or something).
- =org-books-add-to-top= (default t) tells whether to add the book at the top or bottom under the selected heading.

**** org-ref
#+begin_src emacs-lisp
(require 'org-ref)
(setq reftex-default-bibliography '("~/Librarian/Bibliography/default.bib"))
(setq org-ref-bibliography-notes "~/Librarian/Annotations/annotations.org")
(setq org-ref-default-bibliography "~/Librarian/Bibliography/default.bib")
(setq org-ref-pdf-directory "~/Librarian/PDFs")
#+end_src

**** org-noter
#+begin_src emacs-lisp
(use-package org-noter
  :ensure t
  :after org
  :config
  (setq org-noter-default-notes-file-names '("~/Librarian/Annotations/annotations.org")
        org-noter-notes-search-path '("~/Librarian/Annotations"))
  (setq org-noter-separate-notes-from-heading t))
#+end_src

***** org-noter and org-ref
Add reference from org-ref cite-link interface =C-c j= and then open with pdf-tools package.
For files with multiple refs jump to notes using the following funtion:
#+begin_src emacs-lisp
(defun org-ref-note-at-point ()
  "Open odf for citekey under point if exists."
  (interactive)
  (let* ((results (org-ref-get-bibtex-key-and-file))
         (key (car results))
         (pdf-file (funcall org-ref-get-pdf-filename-function key)))
    (if (file-exists-p pdf-file)
        (progn
          (find-file-other-window pdf-file)
          (org-noter))
      (message "No pdf found for %s" key))))
(add-to-list 'org-ref-helm-user-candidates
             '("Annotations" . org-ref-note-at-point))
#+end_src

**** helm-bibtex
#+begin_src emacs-lisp
(require 'helm-bibtex)
(setq bibtex-completion-bibliography "~/Librarian/Bibliography/default.bib")
(setq bibtex-completion-library-path "~/Librarian/PDFs")
(setq bibtex-completion-notes-path "~/Librarian/Annotations")
#+end_src

***** INPROGRESS Citekey Format
The format I prefer for my citekeys is =[LastYear]=
Where =Last= is the surname of the author, and =Year= is the four digit year of the publication. 
If the author has more than one publication in a year then the letters =a, b, c= are added to each successive cited publication. For example, =[Harvey2001]=
=[Harvey2001a]=
=[Harvey2001b]=
Are the publications by Harvey that I have listed in my bibliography for the year of 2001.

**** doi-utils
The following text is from the org-ref documentation for =doi-utils=

Provides two commands:

- =doi-utils-add-bibtex-entry-from-doi=
This will prompt you for a DOI, and a bibtex file, and then try to get the bibtex entry, and pdf of the article.

- =doi-utils-add-entry-from-crossref-query=
This will prompt you for a query string, which is usually the title of an article, or a free-form text citation of an article. 
Then you will get a helm buffer of matching items, which you can choose from to insert a new bibtex entry into a bibtex file.

This library also redefines the org-mode doi link. Now, when you click on this link you will get a menu of options, e.g. to open a bibtex entry or a pdf if you have it, or to search the doi in some scientific search engines. 

***** Troubleshooting doi-utils
Occasionally weird things happen with a DOI. 

The first thing you should check is if the json data for the DOI can be retrieved. You can do that at the command line, or in a sh block like this:

=curl -LH "Accept: application/citeproc+json" "http://doi.org/10.1021/jp511426q"=

If you do not get json data, doi-utils will not be able to generate the bibtex entry.

*Not all PDFs can be retrieved.* doi-utils uses a set of functions to attempt this.

=doi-utils-pdf-url-functions=

You can check if a url for the PDF can be found like this:
=(doi-utils-get-pdf-url "10.1021/jp511426q")=

#+begin_src emacs-lisp
(require 'doi-utils)
#+end_src

**** pdf-tools
Favorite pdf annotation tool

#+begin_src emacs-lisp
(defun bun-save-buffer-no-args ()
  "Save buffer ignoring arguments."
  (save-buffer))
#+end_src

#+BEGIN_SRC emacs-lisp
(use-package pdf-tools
  :pin manual
  :ensure t
  :mode ("\\.pdf\\'" . pdf-view-mode)
  :config
  (pdf-tools-install)
  (setq-default pdf-view-display-size 'fit-page)
  (setq pdf-annot-activate-created-annotations t)
  (define-key pdf-view-mode-map (kbd "C-s") 'isearch-forward)
  (add-hook 'pdf-view-mode-hook (lambda () (cua-mode 0)))
  (setq pdf-view-resize-factor 1.1)
  (define-key pdf-view-mode-map (kbd "h") 'pdf-annot-add-highlight-markup-annotation)
  (define-key pdf-view-mode-map (kbd "t") 'pdf-annot-add-text-annotation)
  (define-key pdf-view-mode-map (kbd "D") 'pdf-annot-delete)
  (with-eval-after-load "pdf-annot"
    (define-key pdf-annot-edit-contents-minor-mode-map (kbd "<return>") 'pdf-annot-edit-contents-commit)
    (define-key pdf-annot-edit-contents-minor-mode-map (kbd "<S-return>") 'newline)
    (advice-add 'pdf-annot-edit-contents-commit :after 'bun-save-buffer-no-args)))
#+END_SRC

***** Troubleshooting PDF-Tools
If =(pdf-tools-install)= does not find libffi on macOS, try:
#+begin_verse
(setenv "PKG_CONFIG_PATH"
        (f-join
         (file-name-as-directory
          (nth 0
               (split-string
                (shell-command-to-string "brew --prefix"))))
         "Cellar" "libffi" "3.2.1" "lib" "pkgconfig"))
#+end_verse
I set my pkgconfig path in my =.bash_profile= and had no issues with this version of Emacs, however =pdf-tools= was broken for me in the stable version.

**** org-pdf-tools
#+BEGIN_SRC emacs-lisp
(use-package org-pdftools
  :hook (org-load . org-pdftools-setup-link))
#+END_SRC

#+BEGIN_SRC emacs-lisp
(use-package org-noter-pdftools
  :after org-noter
  :config
  (with-eval-after-load 'pdf-annot
    (add-hook 'pdf-annot-activate-handler-functions #'org-noter-pdftools-jump-to-note)))
#+END_SRC

**** pdf-tools-org
#+begin_src emacs-lisp
(add-to-list 'load-path "~/.emacs.d/vendor/pdf-tools-org.el")
(require 'pdf-tools-org)
(add-hook 'after-save-hook
          (lambda ()
            (when (eq major-mode 'pdf-view-mode) (pdf-tools-org-export-to-org))))
#+end_src


** Python
#+BEGIN_SRC emacs-lisp
(use-package python
  :ensure nil
  :hook (python-mode . turn-on-prettify-symbols-mode))
#+END_SRC


** YAML
#+BEGIN_SRC emacs-lisp
(use-package yaml-mode
  :mode ("\\.yml\\'"))
#+END_SRC
